# Generated by Django 4.2.7 on 2026-01-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
